services:
  - type: web
    name: musix-api
    runtime: node
    plan: free
    rootDir: BACKEND
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://musix-web.onrender.com

  - type: web
    name: musix-web
    runtime: static
    rootDir: FRONTEND
    buildCommand: npm install && npm run build
    staticPublishPath: FRONTEND/dist
    envVars:
      - key: VITE_API_URL
        value: https://musix-api-61df.onrender.com
